// <auto-generated />
using System;
using Erica.MQ.Services.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Erica.MQ.Migrations
{
    [DbContext(typeof(EricaMQ_DBContext))]
    partial class EricaMQ_DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Erica.MQ.Models.SQL.EricaMQ_Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Context");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("Data");

                    b.Property<string>("FileAttachmentGUID");

                    b.Property<DateTime>("ModifiedDateTime");

                    b.Property<string>("Sender");

                    b.HasKey("Id");

                    b.ToTable("EricaMQ_Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
